import React, { useState, useEffect } from 'react';
import {
  Container,
  Paper,
  Typography,
  Box,
  Button,
  Grid,
  Card,
  CardContent,
  CardActions,
  LinearProgress,
} from '@mui/material';
import { insights } from '../../services/api';
import { toast } from 'react-toastify';

const AIInsights = () => {
  const [loading, setLoading] = useState(true);
  const [insightData, setInsightData] = useState([]);

  useEffect(() => {
    const fetchInsights = async () => {
      try {
        const response = await insights.getAll();
        setInsightData(response.data);
      } catch (error) {
        toast.error('Failed to load insights');
      } finally {
        setLoading(false);
      }
    };

    fetchInsights();
  }, []);

  if (loading) {
    return <LinearProgress />;
  }

  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Paper elevation={3} sx={{ p: 4, borderRadius: 2 }}>
        <Typography variant="h4" component="h1" gutterBottom>
          AI Insights
        </Typography>
        <Typography variant="body2" color="text.secondary" paragraph>
          Here are your latest insights generated by our AI.
        </Typography>

        <Grid container spacing={3}>
          {insightData.map((insight) => (
            <Grid item xs={12} sm={6} md={4} key={insight.id}>
              <Card>
                <CardContent>
                  <Typography variant="h6">{insight.title}</Typography>
                  <Typography variant="body2" color="text.secondary">
                    {insight.summary}
                  </Typography>
                </CardContent>
                <CardActions>
                  <Button size="small" onClick={() => alert(insight.details)}>
                    View Details
                  </Button>
                </CardActions>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Paper>
    </Container>
  );
};

export default AIInsights;